server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 123456

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
