server:
  port: ${PORT:8081}

  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/bank}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:123456}

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
